### ISSUE TITLE
Overall period of treatment

### ISSUE THREAD

**Issue by costateixeira** [IHE/pharm-mpd#43]
In some specifications, for example in Netherlands, there is a need to express the overall timing of the treatment. Currently, dosage allows for a "flat" set of instructions, but no overarching timing and quantity.

For example,
Medication is meant to be taken for three weeks with a different dosaging scheme for every week:
1) 23.08.2024-29.08.2024 Dosaging 1
2) 30.08.2024-06.09.2024 Dosaging 2
3) 07.09.2024-13.09.2024 Dosaging 3
Overall period of treatment would be: 23.08.2024-13.09.2024

While it is possible to calculate the dates from dosage schemes, some countries (The Netherlands, Sweden, Finland) use an extension to show the overall period of treatment in case of multiple dosages.
Also, other related extensions exist, so in the model, we should consider if we need a class to convey the common elements that overarch all dosages.

**Comment by rlindstrm** [comment]
Samuel Danhardt (Lux)
 
I would understand like the Netherlands that period of treatment = from the beginning of first dosaging to the end of the last dosaging. We kinda let this open in our specification, thinking “let’s see how implementers reacts”.

I would have 2 comments :

Using dedicated fields to store the date of each dosing scheme and the total date: here, we may have to be careful that the dates match. For example, shall the request be refused if the last date of the last dosing scheme does not correspond to the last date of the whole intake ?

If we consider that the dates are calculated by the prescriber (or pharmacy) system, why not letting them calculate “on-the-fly” and not take the risk to accept storing incoherent information ? I take here the point of view of a national system storing prescriptions.

**Comment by Monstermanu** [comment]
During the conception of the first version of the trial IG in France, this has been pointed out. It was decided to cope with "calculating" the overall period until migration to FHIR R5 (or higher) as we understand the issue is solved by MedicationRequest.effectiveDosePreriod

**Comment by rlindstrm** [comment]
I had not noticed the existence of MedicationRequest.effectiveDosePeriod... 
I think that if a data element exists in R5 and is needed by at least some countries who use R4, we have a case for creating an extension for R4 only.

**Comment by rlindstrm** [comment]
From Kari:
Granted, my notes do not exactly match the current development stage of Finnish CDA-based model (but I don't see the official documentation being forthcoming either) and the model is admittedly quite complicated for the notorious "basic use cases". BUT.

Similarly to having Medication described explicitly by attributes, the dosage needs similar treatment for MPD context. As there exist national schemas where dosage is e.g. indicated by largely opaque (for xBorder use) coding.
nevertheless highlights problems in the traditional FHIR flat list design. Even in relatively simple cases some data elements need to be repeated for each Dosage instance, creating a risk for discrepancy and/or requiring some logic to make data more understandable to user. Essentially re-creating the dosage-entity hierarchy that existed prior to conversion to FHIR.

**Comment by rlindstrm** [comment]
From Kari:
Speaking for Finland, it's not just about having an extension for overall treatment period (or all the other ones in FI MedReq profile related to dosage). In fact there is a national, multi-level, albeit not perfect, data model behind the dosage (i.e. as expressed in eP CDA documents). Which then has, of course, issues when "forced" to FHIR for our facade API - for one, because FHIR necessitates repeating information as a side-effect of flattening this hierarchy.

So as a very quick&dirty, very draft like class hierarchy going from top, logical model should be something like:

**Dosage_All_Periods class**
probably single required instance (others are nested and allow repeats) in prescription for e.g.

- aggregated data like the overall treatment duration
- data retrieved from background systems like maxDose-related elements
- patient attributes generally affecting dosage like weight or age group (children, elderly)

**Dosage_Period class**

- single period of treatment using a given dosage schedule
- main place for patient instructions
- has status to allow pausing ongoing schedule and still retaining the structure for later use
- having some idea of medication quantity for period needed to execute would greatly simplify dispense tracking

**Dosage_All_Doses class**

- common attributes for all doses, e.g. site/route/method are likely to remain same
- TBD how combi-pack dosage works in a structured form. Each component could form an instance of this class with internal link to contained Medication resource; or just separating these doses by their common attributes to “form a common title” might be enough

**Dosage_Dose class**

- basically maps to majority of elements in current FHIR Dosage where instances have same .sequence identifier
- multiples are "commonly" needed due to way .timing and .doseAndRate interact when latter is not constant for all instances

There are also attributes that should be allowed at all/different levels as their meaning depends on context. First to come in mind is .asNeeded/.asNeededFor; there is a marked semantic difference whether appearing in Dosage_Period / Dosage_All_Doses / Dosage_Dose (and to some extent differ from e.g. using lower bound of 0 in dose quantity to signal optionality). Same goes for the coded .additionalInstruction; if this actually applies to every individual dose, the forced repeats in all Dosage –instances (for varying doses) is problematic.

In a way I do see a parallel between approaches used to representing detailed MedicalProduct and Dosage info in MedReq. One way is to use "just a coding" backed by terminology services with minimal use of actual FHIR elements (mainly plain texts for patient). Another is explicitly having all relevant structured attributes available in FHIR recource (like work on MPD Medication). And there is a massive difference on how well (and for former, if at all) these support non-national and/or cross-border use cases. Or even the national needs (statistics, research etc.) on longer time frame i.e. retrieving accurate, valid data for any code at the time of its use is not a trivial task.

**Comment by costateixeira** [comment]
we can preadopt the R5 element as extension

**Comment by rlindstrm** [comment]
R5 element effectiveDosePeriod preadopted in R4 EU IG
